### ISSUE TITLE
Provide "high watermark" allocator for PX4

### ISSUE THREAD

**Issue by thirtytwobits** [OpenCyphal-Garage/libcyphal#263]
As part of #236 we need to provide a heap allocator that has some specific requirements for px4. @pavel-kirienko or @davids5 should have the requirements.

**Comment by pavel-kirienko** [comment]
The high-level business requirement is to make PX4 maintainers happy.

We have empirically established that the following implementation is likely compatible with the business requirement:

https://github.com/UAVCAN/libuavcan/blob/master/libuavcan/include/uavcan/helpers/heap_based_pool_allocator.hpp

On the technical level, besides the obvious allocate/deallocate we also need `shrink()` which free()s all blocks that are not currently in use. This is useful because certain procedures such as firmware update may temporarily raise the watermark considerably, leaving the UAVCAN process with memory it no longer needs.
